sudo: true
language: python
python:
  - 2.7
before_install:
    - sudo apt-get update
    - sudo apt-get install -y build-essential procps lsb-release
    - sudo mkdir -p ~/.cache
script:
  - sudo make install